# dot2world 設定 (拡張)
TILE_PX: 32
EMBED_TOP_K: 8
SD_RESOLUTION: 512
SD_STEPS_LIGHT: 20
SD_STEPS_HIGH: 50
MAX_CONCURRENT_WORKERS: 4
PER_TILE_COOLDOWN: 5
CANVAS_WIDTH: 22400
CANVAS_HEIGHT: 21966
ASSETS_DIR: assets
GLB_SUBDIR: glb
CACHE_DIR: backend/cache
OBJECTS_JSON: objects.json
ENABLE_REFINER: true
REFINE_DELAY_SEC: 5
# TripoSR 設定 (外部リポジトリへのパス)
TRIPOSR_DIR: "E:\\GITS\\TripoSR-main"
TRIPOSR_PY: "run.py"
TRIPOSR_BAKE_TEXTURE: true
TRIPOSR_OUTPUT_FORMAT: "obj"
# Path to a dedicated Python executable (venv) for running TripoSR. If set,
# the server will invoke this Python to run TripoSR instead of the server's
# own interpreter. Example on Windows:
# TRIPOSR_PYTHON: "C:\\Users\\s-rin\\Documents\\GitHub\\GeoPlace\\venv-triposr\\Scripts\\python.exe"
TRIPOSR_PYTHON: "C:\\Users\\s-rin\\Documents\\GitHub\\GeoPlace\\venv-triposr\\Scripts\\python.exe"
# Stable Diffusion のモデル ID (diffusers)
SD_MODEL_ID: "runwayml/stable-diffusion-v1-5"
SD_VENV_PYTHON: "C:\\Users\\s-rin\\Documents\\GitHub\\GeoPlace\\venv-sd\\Scripts\\python.exe"

# VLM (Vision Language Model) 設定
# VLM_URL: LMStudio/Gemma3 の HTTP エンドポイント（設定すれば HTTP POST で呼び出し）
VLM_URL: "http://localhost:1234/v1/chat/completions"  # LMStudio の標準エンドポイント
#VLM_URL: "http://127.0.0.1:8002"  # ローカルテスト用 mock VLM サーバ
VLM_TOKEN: null  # 認証トークン（LMStudio で必要な場合）
VLM_TIMEOUT: 15  # タイムアウト秒数
VLM_RETRIES: 3   # リトライ回数
# Optional: PUBLIC_URL can be set when exposing the local server via a tunnel (eg. ngrok).
# Example: PUBLIC_URL: "https://abcd-1234.ngrok-free.app"
PUBLIC_URL: http://rinnas.f5.si:8001
